### ISSUE TITLE
A suggestion to add the code for nextJs 13 App router 

### ISSUE THREAD

**Issue by kanishak11-cyber** [thirdweb-dev/docs#1045]
As we already now NEXTJS is doing great and evolving constantly . One of there major update is Its APP ROUTER which is easy to use but if some one is building with app router there is many point where Newbie can stuck. it would be great if someone  also add the App Router Code snippet there too.

I'm also open to contribute in the documentation.

**Comment by MananTank** [comment]
Hey @kanishak11-cyber, 

You can refer to "Get Started" section for Next.js 13 App router instructions 

https://portal.thirdweb.com/react/getting-started

<img width="1010" alt="image" src="https://github.com/thirdweb-dev/docs/assets/22043396/9130b9a5-002b-4abd-9e07-34b715deed6d">
