### ISSUE TITLE
Mismatch between code example and type information

### ISSUE THREAD

**Issue by funwarioisii** [thirdweb-dev/docs#949]
About https://github.com/thirdweb-dev/docs/blob/25c21ff2a6176e5c2e6b95acaccd47ef7d7a362f/docs/typescript/thirdwebsdk.fromsigner.mdx#L23-L26

In this example, the second argument passes an object containing the `clientId` and `secretKey`.

However, the following type information shows that no object containing those two is passed.
The documentation needs to be corrected.

https://github.com/thirdweb-dev/js/blob/ec36b13a30e0071548df0b7a6eb5299e2e65e4f9/packages/sdk/src/evm/core/sdk.ts#L181-L186

https://github.com/thirdweb-dev/js/blob/ec36b13a30e0071548df0b7a6eb5299e2e65e4f9/packages/chains/src/types.ts#L15-L46

**Comment by ciaranightingale** [comment]
the `options` paramter is of type SDKOptions which includes clientID & secretKey - they are required to instantiate the SDK. Hope this solves your concern
